routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/


Auth::routes();

Route::get('/', 'HomeController@index');

//Route::get('/home', 'HomeController@index')->name('home');

Route::resource('posts', 'PostController');

Route::resource('comments', 'CommentController');
Route::post('/comments/{post}/create', 'CommentController@store');

Route::resource('reactions', 'ReactionController');

app/Post.php
<?php

namespace App;

use App\Power;
use App\TypeReaction;
use App\Comment;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public $fillable = ['message','picture','user_id'];

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function comments() {
         return $this->hasMany('App\Comment');
     }

    public function reaction() {
         return $this->hasMany('App\Reaction');
     }
      
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;


use App\Post;
use Illuminate\Http\Request;

class PostController extends CheckAuthController
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('post')
        ->withPosts(Post::all()->reverse());

                
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        {
            return view('posts.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        {
            $name = $request->picture->getClientOriginalName();
            $store = $request->picture->storeAs('public/images', $name);

            $parameters = $request->validate([
                'message' => 'nullable',
                'picture' => 'nullable',
    
            ]);

            $parameters['user_id'] = auth()->user()->id;
            $parameters['picture'] = $name;
            Post::create ( $parameters );
    
            return redirect()->route('posts.index');        
        }
    }

    
    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show (Post $post)
    {
        //          
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {     
     //   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
    }
}

resources/views/posts/create.blade.php
    @include('errors')
 
      
    <form class="form-group" action="{{ route('posts.store')}}" method="post" enctype="multipart/form-data"> 

            @csrf {{--protection de formulaire laravel--}}
            
            <div class="form-group">
                    
                        <textarea class="form-control" name="message" rows="15" placeholder="Créer un nouveau post !"></textarea>
                        
                        <label for="exampleFormControlFile1">Inserer une image</label>
                        <input type="file" name="picture" class="form-control-file">

                    <input type="submit" value="Valider"> 
            </div>

    </form>
    
    





    

resources/views/posts/show.blade.php
         <div>
            
            @foreach ($posts as $post)
            <div class="shadow p-3 mb-5 bg-white rounded" >
                <div class="shadow p-3 mb-5 bg-white rounded">
                    <div class="d-flex">
                        <p class="font-weight-bold"> Publié par &nbsp; {{ $post->user->firstname }} </p>
                        <p > &nbsp; posté le  {{ $post->created_at }}  </p> 
                    </div>

                        <p> {{ $post->message }} </p><br>
                        <div>
                            @if ($post->picture)
                                
                                <img src="{{ asset('storage/images/' . $post->picture) }}" width="30%" />

                            @endif
                        </div>
                        @include('reactions/create')
                            
                    </div>
                
                @include('comments/show')
                @include('comments/create')
            </div>
            @endforeach
            


            {{-- <p> {{ affiche le post }}</p> --}}
        </div>   




  
   
        